# GitHub Actions Workflow with MATLAB Actions

# Copyright 2022 The MathWorks, Inc.

name: Check MATLAB Project

on:
  push:
    branches:
    - 'R2022b'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

jobs:
  matlab-project-check-22a:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2022b

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); HEVProject_runtests_CheckProject;
