# GitHub Actions Workflow with MATLAB Actions

# Copyright 2021 The MathWorks, Inc.

name: MATLAB Build

on:

  push:
    branches: [ main, 21a-devel ]

  pull_request:
    branches: [ main, 21a-devel ]

jobs:
  matlab-job-21b:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2021b

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); runTests_Project;

  matlab-job-21a:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2021a

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); runTests_Project;
